<Project>
    <PropertyGroup>
        <TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591;IDE0130;</NoWarn>
        <Authors>huanent</Authors>
        <AssemblyName>VoidNone.$(MSBuildProjectName)</AssemblyName>
        <RootNamespace>VoidNone.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/voidnone/dotnet-extensions</PackageProjectUrl>
        <RepositoryUrl>https://github.com/voidnone/dotnet-extensions.git</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
</Project>